### PR TITLE
Implements`blockchain.scripthash.get_mempool` method for RPC

### LINKED ISSUE #839: Feature: Implement `blockchain.scripthash.get_mempool` method for RPC
Implement `blockchain.scripthash.get_mempool` as described in the documentation [here](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-get-mempool), so that we provide support for all methods

### PR DESCRIPTION
**Pull request by EshaanAgg**
Fixes #839 
Implements the `blockchain.scripthash.get_mempool` method with reference to [here](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-get-mempool)

### CODE REVIEW

**Comment by EshaanAgg** [comment]
@romanz 
I would like some help while implementing this method.
1. I can't figure out a way to get the transaction fees for each transaction, thus I have hard-coded it to 123. Can you guide me as to how to get the same?
2. I have to make some fields `pub` on some `structs` to get the needed data. Is this okay, or should we move to creating `getters` for these properties in these `structs`? 

Thanks for your patience :)

**Comment by romanz** [comment]
It doesn't seems that this RPC is being used by Electrum wallet:
https://github.com/search?q=repo%3Aspesmilo%2Felectrum%20blockchain.scripthash.get_mempool&type=code

Are you familiar with other wallets using this RPC?

**Comment by EshaanAgg** [comment]
I am not. I just saw in the ElectrumX docs, so figured it must be supported by Electrum.
Without support in Electrum, implementation of the same is moot.

**Comment by romanz** [comment]
Closing for now, let's re-open in case this RPC will be in use.

**Pull request closed without merging**
