### PR TITLE
Replace RocksDB with sled

### PR DESCRIPTION
**Pull request by KhaledEmaraDev**

### CODE REVIEW

**Comment by Kixunil** [comment]
AFAIK `sled` is worse than rocksdb, so it should be compile-time selectable, ideally using Clean Architecture.

**Comment by KhaledEmaraDev** [comment]
@Kixunil I'm working on making both implement a trait. Should I convert this PR to a draft one?

**Comment by Kixunil** [comment]
@KhaledEmaraDev I think it's a good idea

**Comment by romanz** [comment]
@KhaledEmaraDev Thanks for opening this PR!
Could you please adapt it to support both DBs, and attach the sled performance metrics?

**Comment by KhaledEmaraDev** [comment]
@romanz working on it.

**Comment by romanz** [comment]
We should also consider https://github.com/cberner/redb, following https://github.com/romanz/electrs/issues/753.

**Comment by KhaledEmaraDev** [comment]
@romanz Will work on including it.

**Comment by casey** [comment]
btw, the author of redb just added benchmarks vs rocksdb, and it looks like it's way faster: https://github.com/cberner/redb#benchmarks

**Comment by Kixunil** [comment]
Wow, that looks great! Add some RPC optimizations and we may finally fix perf issues.

**Comment by KhaledEmaraDev** [comment]
This is replaced by #765.

**Pull request closed without merging**
