### PR TITLE
Allow setting cookie via CLI flag or ENV var

### LINKED ISSUE #189: Allow cookie to be set via CLI flag or ENV var
>In addition, config files support cookie option to specify cookie - this is not available using command line or environment variables for security reasons (other applications could read it otherwise).

This good practise in general, however there are some scenarios where it may be useful to allow setting cookie via CLI flag or ENV var where it's not a security concern.

For example, in an isolated Docker network I just use the credentials `rpcuser:rpcpassword`. It's easy set between different containers and the RPC port isn't even accessible by the host, it's only internal to the Docker network.

To get this working with electrs I need to create a config file purely to set the cookie which is awkward. It would be great if I could just add `ELECTRS_COOKIE=rpcuser:rpcpassword` to my `docker-compose.yml`.

Are you open to allowing this?

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves #189

### CODE REVIEW

**Comment by oleiba** [comment]
I believe it is intentionally not available as an ENV variable or CLI flag.
from [Usage.md](https://github.com/romanz/electrs/blob/master/doc/usage.md):
```
In addition, config files support cookie option to specify cookie - this is not available using command line or environment variables for security reasonns (other applications could read it otherwise).
```

**Comment by lukechilds** [comment]
Yeah I'm aware it's intentional, see related issue for context: https://github.com/romanz/electrs/issues/189

**Comment by romanz** [comment]
Please try to use `--cookie-file` (see 5549287).

**Comment by romanz** [comment]
Ping :)

**Comment by lukechilds** [comment]
@romanz sorry, missed this!

I was just benchmarking electrs/ElectrumX against each other in a virtual machine for research purposes.

I've finished my tests and destroyed the machine now so this isn't something I need right now or can easily test.

`--cookie-file` definitely looks like a good solution to the problem though!

**Pull request closed without merging**
