### PR TITLE
Use atomic u64 instead of Mutex for counter

### PR DESCRIPTION
**Pull request by Kixunil**
This change switches from `Mutex<u64>` to `AtomicU64`, which is faster
and somewhat more elegant to write. It keeps the `Counter` type for
backwards compatibility.

The downside is that it doesn't work on as many platforms and requires
fairly recent compiler.

### CODE REVIEW

**Comment by Kixunil** [comment]
See [the documentation for `std::sync::atomic`](https://doc.rust-lang.org/std/sync/atomic/index.html) for more details about atomics.

**Comment by romanz** [comment]
Thanks a lot for the PR!

The only question that I have is whether the new code runs on ARM-based devices (e.g. Raspberry Pi)?
/cc @sangaman @duckartes @jimmyongit

**Comment by Stadicus** [comment]
I just compiled https://github.com/romanz/electrs/pull/144/commits/2a835d94ef8e99a9b53a2952936c69320171429b on a RockPro64 aarch64 board. No issues, runs fine without further testing.

```
$ clang --version
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
One warning during compilation, probably not relevant:
```
   Compiling librocksdb-sys v5.18.3
warning: redundant linker flag specified for library `stdc++`
```

**Comment by romanz** [comment]
Unfortunately, it doesn't compile on Rust 1.32 (which is the current Debian version).
Will merge it after Debian updates to a more recent version.

**Comment by Kixunil** [comment]
I was thinking that maybe a feature flag would help. It'd help with the other unsupported architectures as well. Thanks to the way `Counter` is implemented it'd be easy to do.

What do you think?

**Comment by romanz** [comment]
Using a feature flag sounds great.
Could you please update the PR?

**Comment by romanz** [comment]
Many thanks, I have added a feature flag for "latest" Rust support :)

**Comment by Kixunil** [comment]
You are welcome. I wanted to do it myself but I was quite busy lately.

**Pull request merged**
