### PR TITLE
Add asciinema screencasts for quickstart installation and usage

### PR DESCRIPTION
**Pull request by romanz**
Following #619

### CODE REVIEW

**Comment by romanz** [comment]
CC: @k3tan172 @Kixunil

**Comment by Kixunil** [comment]
I think we should somehow briefly document when the quickstarts are applicable so that people know whether the assumptions about their system are correct.

**Comment by romanz** [comment]
Added a short `details` section before each screencast - WDYT?

**Review by Kixunil — APPROVED** [review]
Looks good, we'll see if it helps after merging I guess...

**Pull request merged**
