### PR TITLE
Parse p2p messages in a separate thread

### PR DESCRIPTION
**Pull request by romanz**
Also, use a separate metrics for parsing duration monitoring.

### CODE REVIEW

**Comment by romanz** [comment]
Note that even with warm cache, we are bottlenecked on getting the blocks from bitcoind.
If we run the following command:
```
$ netcat 127.0.0.1 50001 < _etc/_all12_subs.txt
```
we get the following metrics:

## on this branch
```
$ curl -s localhost:4224 | grep -E 'recv.*sum'; curl -s localhost:4224 | grep -E 'rpc.*sum'
p2p_recv_duration_sum{step="recv_alert"} 0.000119866
p2p_recv_duration_sum{step="recv_block"} 4.257350154000001
p2p_recv_duration_sum{step="recv_headers"} 10.867462993
p2p_recv_duration_sum{step="recv_ping"} 0.000394555
p2p_recv_duration_sum{step="recv_verack"} 0.000013135
p2p_recv_duration_sum{step="recv_version"} 0.000810401
p2p_recv_duration_sum{step="wait"} 0.0016755499999999998
p2p_recv_size_sum{message="alert"} 168
p2p_recv_size_sum{message="block"} 476122083
p2p_recv_size_sum{message="headers"} 86
p2p_recv_size_sum{message="ping"} 8
p2p_recv_size_sum{message="verack"} 0
p2p_recv_size_sum{message="version"} 103
rpc_duration_sum{method="blockchain.scripthash.subscribe:multi"} 4.195365789
```
## on master 
```
$ curl -s localhost:4224 | grep -E 'recv.*sum'; curl -s localhost:4224 | grep -E 'rpc.*sum'
p2p_recv_duration_sum{step="parse_alert"} 0.000000722
p2p_recv_duration_sum{step="parse_block"} 0.9869173709999995
p2p_recv_duration_sum{step="parse_headers"} 0.000004859
p2p_recv_duration_sum{step="parse_ping"} 0.00000012
p2p_recv_duration_sum{step="parse_verack"} 0.000000201
p2p_recv_duration_sum{step="parse_version"} 0.000002935
p2p_recv_duration_sum{step="recv_alert"} 0.000103827
p2p_recv_duration_sum{step="recv_block"} 3.3341250019999995
p2p_recv_duration_sum{step="recv_headers"} 6.191992845000001
p2p_recv_duration_sum{step="recv_ping"} 0.000325536
p2p_recv_duration_sum{step="recv_verack"} 0.000006573
p2p_recv_duration_sum{step="recv_version"} 0.000811002
p2p_recv_duration_sum{step="wait"} 0.0018909809999999977
p2p_recv_size_sum{message="alert"} 168
p2p_recv_size_sum{message="block"} 475522181
p2p_recv_size_sum{message="headers"} 4
p2p_recv_size_sum{message="ping"} 8
p2p_recv_size_sum{message="verack"} 0
p2p_recv_size_sum{message="version"} 103
rpc_duration_sum{method="blockchain.scripthash.subscribe:multi"} 4.283185838
```

**Comment by romanz** [comment]
i.e. it takes ~4.2 seconds - even if the parsing takes place in the receiver's thread.

**Comment by Kixunil** [comment]
It sucks that additional connections would take up slots and mess up bitcoind P2P algorithm. One way of dealing with this would be adding another highly-optimized interface to Bitcoind that allows fetching public data. Not sure if Core devs would be happy with it though.

**Comment by romanz** [comment]
> One way of dealing with this would be adding another highly-optimized interface to Bitcoind that allows fetching public data.

WDYT about https://github.com/bitcoin/bitcoin/compare/master...romanz:get-tx-rpc?

**Comment by Kixunil** [comment]
I see two problems with it:

* Messing with offsets which got rejected the last time. Any offsets need to come from the internal bitcoind database to be reliable.
* Json RPC is not very performant in general, not sure what's causing it, but my guess would be HTTP+Json handling, perhaps with lack of multithreading/async.

I was thinking of a very tiny binary protocol:

`OP,ARGS_TAG,ARGS -> OK/ERR,PAYLOAD`

`OP` - 1B, 00 - get block, 01 - get transaction
`ARGS_TAG` - 1B, 00 for get block by height, 01 for get block by hash; 00 for get transaction by hash
`ARGS`: 8B big-endian block height or 32B hash (of block or tx, depending on `ARGS_TAG`)

Response: `00` - `OK`, `01`-`ERR`
`PAYLOAD` - binary block/transaction, in case of error some error code (4B should be enoug)

The interface should support Unix sockets.

**Comment by romanz** [comment]
Tested by fetching the coinbase tx from a large block:
```
$ time bitcoin-cli getrawtransaction 543bd12a9d98805ab635f477eaf55b5144747f6ab5ec79251d6c8e8112e54e16 0 00000000000000000000987fc51e94a74a12e5715a17d2873e4c52d7d8ef6c7d 83
010000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff640338e00a2cfabe6d6d2e9d81bf40810289aa037e3d4536d107958beb87efe8b7f6ed2855a034a5d4ce10000000f09f909f092f4632506f6f6c2f6d000000000000000000000000000000000000000000000000000000000000000000000005001b68000000000000057156b725000000001976a914c825a1ecf2a6830c4401620c3a16f1995057c2ab88ac0000000000000000266a24aa21a9ed8140267d3890e7e3bb27ca55ea64f3798289c24de99ad7471123fb0eece036870000000000000000266a2448617468fb4e7cde9182937e579334bca4b8c7580e511706eeff7bafa2baa926447fee8600000000000000002c6a4c2952534b424c4f434b3a19b92a9c14d35d7e752752f96023116a2f552429bf1d265935658722003b88d10000000000000000266a24b9e11b6d382539b1c2f2c82f486966fbb04db72ec2a92d06e09c2317146a1ab58e533a5001200000000000000000000000000000000000000000000000000000000000000000e6fce53d

real	0m0.005s
user	0m0.004s
sys	0m0.000s

$ time bitcoin-cli getrawtransaction 543bd12a9d98805ab635f477eaf55b5144747f6ab5ec79251d6c8e8112e54e16 0 00000000000000000000987fc51e94a74a12e5715a17d2873e4c52d7d8ef6c7d 0
010000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff640338e00a2cfabe6d6d2e9d81bf40810289aa037e3d4536d107958beb87efe8b7f6ed2855a034a5d4ce10000000f09f909f092f4632506f6f6c2f6d000000000000000000000000000000000000000000000000000000000000000000000005001b68000000000000057156b725000000001976a914c825a1ecf2a6830c4401620c3a16f1995057c2ab88ac0000000000000000266a24aa21a9ed8140267d3890e7e3bb27ca55ea64f3798289c24de99ad7471123fb0eece036870000000000000000266a2448617468fb4e7cde9182937e579334bca4b8c7580e511706eeff7bafa2baa926447fee8600000000000000002c6a4c2952534b424c4f434b3a19b92a9c14d35d7e752752f96023116a2f552429bf1d265935658722003b88d10000000000000000266a24b9e11b6d382539b1c2f2c82f486966fbb04db72ec2a92d06e09c2317146a1ab58e533a5001200000000000000000000000000000000000000000000000000000000000000000e6fce53d

real	0m0.046s
user	0m0.000s
sys	0m0.004s
```

**Comment by Kixunil** [comment]
WTF, reading whole block is faster than a single transaction?

**Comment by romanz** [comment]
The other way around :)

**Comment by romanz** [comment]
My bad... fixing the comments.

**Comment by romanz** [comment]
`offset=0` reads the transaction by loading the whole block.
`offset=83` reads only https://blockstream.info/tx/543bd12a9d98805ab635f477eaf55b5144747f6ab5ec79251d6c8e8112e54e16 from the disk.

**Comment by romanz** [comment]
https://github.com/bitcoin/bitcoin/compare/master...romanz:get-tx-rpc#diff-54409bbc1a072860afa5d3e2c920ac585b819f1db7ba0d894a4c64d7a66f8464R145 allows measure the I/O diff:
```
2021-12-05T19:48:51Z GetTransaction: <...> started
2021-12-05T19:48:51Z GetTransaction: <...> completed (138μs)
2021-12-05T19:48:53Z GetTransaction: <...> started
2021-12-05T19:48:53Z GetTransaction: <...> completed (38692μs)
```

**Comment by Kixunil** [comment]
Damn, that's quite big saving, would be great if we could get it working without problems that Core devs pointed out.

**Comment by Kixunil** [comment]
One idea that comes to mind is adding prefix search to Core. This would require `txindex` but at least it'd be fast and reasonably robust. We could still support short index for those who don't want full txindex.

**Pull request merged**
