### PR TITLE
Use p2p protocol to replace `waitfornewblock` hidden RPC

### PR DESCRIPTION
**Pull request by romanz**
Fixes https://github.com/romanz/electrs/issues/522.

### CODE REVIEW

**Comment by romanz** [comment]
[... with entirely too many Crossbeam Channels](https://rust-unofficial.github.io/too-many-lists/) :)

**Comment by romanz** [comment]
> So if we're unlucky and two threads are waiting for a response the scheduler could wake up the thread that sent the latter request first and that thread would presumably receive the response intended for the other.

Yes, it's indeed currently assumed that `get_new_headers` and `for_blocks` can be called only from one thread (since they are using `&mut self`).

**Comment by Kixunil** [comment]
Ah, yes, `&mut` protects it. So I believe the code is OK, just a bit hazardous in case of refactors?

**Comment by romanz** [comment]
Indeed... I'll add a comment about `&mut` and `new_block_notification` expected usage.

**Pull request merged**
