### PR TITLE
Axum HTTP server feature

### LINKED ISSUE #820: Feature: HTTP RPC API
**Is your feature request related to a problem? Please describe.**
We're currently using Blockstream's Esplora with BDK, but it's quite heavy and out of date with current electrs.

**Describe the solution you'd like**
I've considered making a crate called `electrs-http-proxy` that's just a reimplementation of the Esplora REST API that proxies to wrap electrs. Would this make sense to do as a separate crate?

**Describe alternatives you've considered**
An HTTP server will likely be opinionated and might complicate maintenance of electrs itself, and I'd be open to other implementations behind feature gating, but if I was doing it, I'd probably default to updating the interface to use axum, while referencing the hyper handler interface used by Blockstream.

**Additional context**
For context, a link to the Blockstream fork for Esplora:
https://github.com/Blockstream/electrs

Their REST request handler, using hyper:
https://github.com/Blockstream/electrs/blob/a808b51d0d9301fa82390b985c57551966001f9b/src/rest.rs#L615

I'm open to opinions, advice, especially of anything I might seem to be unaware of.

### PR DESCRIPTION
**Pull request by cryptoquick**
WIP

Closes #820 #904

### CODE REVIEW

**Comment by whfuyn** [comment]
Any update on this one?

**Comment by cryptoquick** [comment]
We realized we already had access to the mempool API on the device, so it no longer makes sense for us to go this route.

**Comment by knocte** [comment]
@cryptoquick what was left to do here? (was it still WIP?) My team might want to pick this up and finish it.

**Comment by cryptoquick** [comment]
@knocte I was never able to get tokio to run the axum server alongside electrs for some reason. It also needs the remaining methods to be implemented.

**Pull request closed without merging**
