### PR TITLE
Add a release note about `db/mainnet` -> `db/bitcoin` rename

### PR DESCRIPTION
**Pull request by romanz**
https://github.com/romanz/electrs/issues/502

### CODE REVIEW

**Comment by Kixunil** [comment]
So if I understand this correctly the code in #477 is bogus because it will create a new directory anyway? If yes, then we should delete it.

**Comment by romanz** [comment]
It's useful for testnet/signet and will be useful for next upgrades :)

**Comment by Kixunil** [comment]
I mean we should delete the directory, not the code. :)

**Comment by romanz** [comment]
You're right, but fixing this would require us to test both `db/mainnet` and `db/bitcoin` - complicating the upgrade code :(

**Comment by Kixunil** [comment]
Hmm, I don't think complication will be *that* bad. Will try to look into it soon but my time is not great lately so it may take two-three days.

**Pull request merged**
