### PR TITLE
Don't fail mempool sync on missing transactions

### PR DESCRIPTION
**Pull request by romanz**
Otherwise, RBF may cause current sync implementation to fail.

### CODE REVIEW

**Comment by romanz** [comment]
It can also handle following transient RPC errors:
```
mempool sync failed: batch getrawtransaction request failed: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)
```

**Comment by antonilol** [comment]
when running this pr on my node i got the following two messages (alongside the usual indexing 1 blocks, chain updated):
`missing mempool entry: 9c75d38a3eeca395a2c6bb6bb4b14bf8126334f16c2da57b7a1753b930890748`
and
`missing mempool tx: f10483eaf7defa69ea77932b0839379466bfa5bec9a8fa9255e7aa0b1dd7ef45`
(checked both on mempool.space and they both have been replaced)

**Comment by antonilol** [comment]
missing mempool tx/entry is common in the log, for replaced transactions.
i did however find a whole list of missing mempool entry warnings followed by `mempool sync failed: batch getmempoolentry request failed: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)`, the transaction ids logged were all confirmed transactions from the same block

**Comment by romanz** [comment]
> is this a problem or just indicates that after replacement it cant be found anymore?

It is not a problem - probably just a regular RBF :)

**Comment by romanz** [comment]
> `Resource temporarily unavailable (os error 11)`

Has this error also happened before this PR?

**Comment by antonilol** [comment]
> > `Resource temporarily unavailable (os error 11)`
> 
> Has this error also happened before this PR?

not that i know of, at least not from 19 (log start) to 28 (first occurrence of that os error) january

**Comment by romanz** [comment]
OK, thanks @antonilol!
I'll merge this PR, and let's continue running it to see how it goes :)

**Pull request merged**
