### PR TITLE
Add Regtest mode

### PR DESCRIPTION
**Pull request by greenaddress**
This PR builds on top of https://github.com/romanz/electrs/pull/19 and adds regtest support

### CODE REVIEW

**Comment by greenaddress** [comment]
It seems regtest mode fails


```
Config { log: StdErrLog { verbosity: Debug, quiet: false, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: Regtest, db_path: "/tmp/db/regtest", daemon_dir: "/root/.bitcoin/regtest", daemon_rpc_url: "127.0.0.1:18443", cookie: "test1:test2", rpc_addr: V4(127.0.0.1:60001), monitoring_addr: V4(127.0.0.1:42024) }
^[[0m^[[36m2018-07-15T19:45:31.516+00:00 - DEBUG - Server listening on 127.0.0.1:42024
^[[0m^[[0m^[[36m2018-07-15T19:45:31.516+00:00 - DEBUG - Running accept thread
^[[0m^[[0m^[[36m2018-07-15T19:45:31.517+00:00 - DEBUG - BlockchainInfo { chain: "regtest", blocks: 864, headers: 864, bestblockhash: "442e65d147d4febc39625f472b215521651d29f7aaeea9305d3aeeb24b9b263c", size_on_disk: 270582, pruned: false }
^[[0m^[[0m^[[36m2018-07-15T19:45:31.518+00:00 - DEBUG - NetworkInfo { version: 160100, subversion: "/Satoshi:0.16.1/" }
^[[0m^[[0m^[[36m2018-07-15T19:45:31.518+00:00 - DEBUG - opening DB at "/tmp/db/regtest"
^[[0m^[[0m^[[33m2018-07-15T19:45:31.537+00:00 - INFO - indexing 0 blk*.dat files
^[[0m^[[0m^[[36m2018-07-15T19:45:31.799+00:00 - DEBUG - applying 865 new headers from height 0
^[[0m^[[0m^[[0m^[[36m^[[36m2018-07-15T19:45:31.802+00:00 - DEBUG - no more blocks to index
2018-07-15T19:45:31.802+00:00 - DEBUG - no more blocks to index
^[[0m^[[0mthread 'bulk_writer' panicked at 'no indexed header found', libcore/option.rs:914:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'writer panicked: Any', libcore/result.rs:945:5

```

**Comment by romanz** [comment]
Thanks for the suggestion!
I'd suggest change the `--testnet` flag into a `--network` "selector", for example:
```rust
.arg(
    Arg::with_name("network")
        .help("Select Bitcoin network type ('mainnet', 'testnet' or 'regtest')"),
)```

**Comment by greenaddress** [comment]
@romanz I'll rebase and have a look

**Comment by romanz** [comment]
> `thread 'bulk_writer' panicked at 'no indexed header found', libcore/option.rs:914:5`

This panic indeed shouldn't happen - thanks for finding this bug!
I'll reproduce and fix it tomorrow :)

**Comment by greenaddress** [comment]
@romanz cool! I've rebased the PR and made it a network selector, is this what you had in mind?

I also run the fmt checker since master broke https://travis-ci.com/romanz/electrs/builds/79030604

**Comment by romanz** [comment]
```
2018-07-15T19:45:31.537+00:00 - INFO - indexing 0 blk*.dat files
```
It seems that `electrs` can't find `blk*.dat` files at `~/.bitcoin/regtest/blocks/`.

**Comment by romanz** [comment]
Please take a look at https://github.com/romanz/electrs/compare/regtest_mode - it seems to run correctly now:
```
$ cargo run --release -- --network regtest -vvvv --timestamp
   Compiling electrs v0.2.0 (file:///home/roman/Code/Bitcoin/elect-rs)
    Finished release [optimized] target(s) in 37.27s
     Running `target/release/electrs --network regtest -vvvv --timestamp`
Config { log: StdErrLog { verbosity: Trace, quiet: false, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: Regtest, db_path: "./db/regtest", daemon_dir: "/home/roman/.bitcoin/regtest", daemon_rpc_addr: V4(127.0.0.1:18443), cookie: "__cookie__:67b98917fcce88637182c00cece9bb7c74f7232c0f81e7b1389db90b4cd878a6", electrum_rpc_addr: V4(127.0.0.1:60401), monitoring_addr: V4(127.0.0.1:42024) }
2018-07-16T09:41:25.668+03:00 - DEBUG - Server listening on 127.0.0.1:42024
2018-07-16T09:41:25.668+03:00 - DEBUG - Running accept thread
2018-07-16T09:41:25.668+03:00 - DEBUG - BlockchainInfo { chain: "regtest", blocks: 0, headers: 0, bestblockhash: "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206", size_on_disk: 293, pruned: false }
2018-07-16T09:41:25.669+03:00 - DEBUG - NetworkInfo { version: 169900, subversion: "/Satoshi:0.16.99/" }
2018-07-16T09:41:25.669+03:00 - DEBUG - opening DB at "./db/regtest"
2018-07-16T09:41:25.919+03:00 - INFO - listing block files at "/home/roman/.bitcoin/regtest/blocks/blk*.dat"
2018-07-16T09:41:25.919+03:00 - INFO - indexing 1 blk*.dat files
2018-07-16T09:41:25.919+03:00 - TRACE - downloading 1 block headers
2018-07-16T09:41:25.920+03:00 - DEBUG - applying 1 new headers from height 0
2018-07-16T09:41:25.927+03:00 - DEBUG - no more blocks to index
2018-07-16T09:41:25.965+03:00 - TRACE - indexed "/home/roman/.bitcoin/regtest/blocks/blk00000.dat": 3 rows
2018-07-16T09:41:25.964+03:00 - DEBUG - no more blocks to index
2018-07-16T09:41:25.965+03:00 - DEBUG - last indexed block: best=0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 height=0 @ 2011-02-02T23:16:42Z
2018-07-16T09:41:26.546+03:00 - INFO - starting full compaction
2018-07-16T09:41:26.757+03:00 - INFO - finished full compaction
2018-07-16T09:41:26.849+03:00 - DEBUG - applying 1 new headers from height 0
2018-07-16T09:41:26.850+03:00 - DEBUG - downloading new block headers (1 already indexed) from 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
2018-07-16T09:41:26.882+03:00 - TRACE - 0 transactions in mempool (+0)
2018-07-16T09:41:26.882+03:00 - INFO - RPC server running on 127.0.0.1:60401
2018-07-16T09:41:31.883+03:00 - TRACE - 0 transactions in mempool (+0)
2018-07-16T09:41:36.884+03:00 - TRACE - 0 transactions in mempool (+0)
2018-07-16T09:41:41.886+03:00 - TRACE - 0 transactions in mempool (+0)
2018-07-16T09:41:46.888+03:00 - TRACE - 0 transactions in mempool (+0)
2018-07-16T09:41:51.889+03:00 - TRACE - 0 transactions in mempool (+0)
```

**Comment by greenaddress** [comment]
@romanz thanks. I will test shortly and let you know

**Pull request merged**
