### PR TITLE
Don't fail on HTTP timeouts from bitcoind RPC

### PR DESCRIPTION
**Pull request by romanz**
It should be OK to retry in case of a RPC timeout.

Should help with https://github.com/romanz/electrs/issues/495.

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
`match` would feel more rust-idiomatic but logic looks good.

**Comment by romanz** [comment]
Thanks!

> `match` would feel more rust-idiomatic but logic looks good.

I agree, but clippy does not :)
https://github.com/romanz/electrs/runs/3723483967?check_suite_focus=true#step:7:89
https://rust-lang.github.io/rust-clippy/master/index.html#single_match

**Comment by Kixunil** [comment]
Was thinking of moving `bail!` into the `_ =>` arm, I believe it should not trigger `clippy` (and if it does I would probably report it as a bug).

**Comment by romanz** [comment]
Not sure if I understand... did you mean:
```rust
    match err {
        JsonRpcError(TransportError(ref e)) if let Some(HttpError::Timeout) = e.downcast_ref::<HttpError>() => {
            // Following https://github.com/romanz/electrs/issues/495
            warn!("ignoring bitcoind HTTP timeout error");
            return Ok(());
        }
        _ => bail!("RPC '{}' failed: {}", name, err), // fail on all other RPC errors
    }
```
Unfortunately, the above code fails to compile with:
```
error[E0658]: `let` expressions in this position are experimental
  --> src/server.rs:56:48
   |
56 |         JsonRpcError(TransportError(ref e)) if let Some(HttpError::Timeout) = e.downcast_ref::<HttpError>() => {
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/53667
```

**Comment by Kixunil** [comment]
Ah, I see the problem now, didn't realize `bail!` would have to be repeated in `else` branch and your example is not supported on stable Rust. OK, let's keep it as it was.

**Pull request merged**
