### PR TITLE
Update tempfile to 3.4.0

### PR DESCRIPTION
**Pull request by romanz**
Following https://github.com/romanz/electrs/security/dependabot/5

### CODE REVIEW

**Comment by Kixunil** [comment]
Looks like you just leaked something?

**Comment by romanz** [comment]
Leaked?

**Comment by romanz** [comment]
IIUC, this is an issue in `tempfile` which is used only by unit-tests.

**Comment by Kixunil** [comment]
The link is inaccessible to me, presumably because the reason you upgraded should be secret.

**Comment by romanz** [comment]
:facepalm:

**Pull request merged**
