### PR TITLE
Release 0.9.0

### PR DESCRIPTION
**Pull request by romanz**
https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md

### CODE REVIEW

**Comment by Pantamis** [comment]
The Time has come.

YOLO

Congrat for your amazing work on this release !

YOLO ACK

**Comment by Kixunil** [comment]
I just wrote the renaming code, it's just a few lines added. Running the test now. Could this wait?

**Comment by romanz** [comment]
Sounds good - will wait for the PR.

**Comment by Kixunil** [comment]
I found it needed a bit more lines to stay correct but still pretty simple I think. See #513

**Comment by romanz** [comment]
https://crates.io/crates/electrs/0.9.0 is now released :)
Many thanks to all the contributors, reviewers and testers - much appreciated!

**Pull request merged**
