### PR TITLE
Upgrade `bitcoin` dependency to 0.31.0

### PR DESCRIPTION
**Pull request by tcharding**
This is not a merge candidate.

Upgrade dependencies required to use the recently released `rust-bitcoin v0.31.0-rc1` release.

Done while trying to upgrade `bdk` to use the bitcoin RC release.

### CODE REVIEW

**Comment by tcharding** [comment]
Bother, I was supposed to be doing `electrsd` not `electrs`. Anyhow, I'll leave this here in case its useful for you later on @romanz.

**Comment by romanz** [comment]
Thanks!

**Comment by romanz** [comment]
Testing `0.31.0-rc2`

**Comment by tcharding** [comment]
No public changes between rc1 an rc2, should be sweet. Thanks for testing man!

**Comment by romanz** [comment]
Squashed and rebased after `rust-bitcoin v0.31.0` release.

**Comment by romanz** [comment]
Synced with https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/313.

**Comment by romanz** [comment]
Many thanks @tcharding!

**Comment by tcharding** [comment]
No worries man, wish I had updated the PR description before you merged :)

**Comment by romanz** [comment]
Oops, you're right - sorry for the quick merge...

**Comment by tcharding** [comment]
My fault, I saw you pushing weeks ago and didn't fix it. Not to worry. Thanks man.

**Pull request merged**
