### PR TITLE
Export mempool metrics grouped by fee band

### LINKED ISSUE #551: Bug: metrics endpoint breaking change.
**Describe the bug**
The metrics for promethius changed and I am wondering why, and whether the information I want is still accessible another way.

**Electrs version**
Which version of `electrs` do you use? Please try to use newest version if possible.
v0.9.0

**To Reproduce**
1. curl http://localhost:4224/metrics

**Expected behavior**
Information about mempool size, number of mempool transactions, and fees.

**Configuration**

<details>
<summary>electrs.toml</summary>

```
verbose = 2
timestamp = true
jsonrpc_import = true
index-batch-size = 10
wait_duration_secs = 10
jsonrpc_timeout_secs = 15
db_dir = "/mnt/hdd/app-storage/electrs/db"
auth = "*********************"
# allow BTC-RPC-explorer show tx-s for addresses with a history of more than 100
txid_limit = 1000
server_banner = "Welcome to electrs v0.9.0 - the Electrum Rust Server on your RaspiBlitz"

```

</details>

Environment variables: 
Arguments: `--electrum-rpc-addr="0.0.0.0:50001`

**System running electrs**
 - Deployment method: manual (which guide did you follow?)/native OS package/Docker
 - OS name and version (name of distribution and version in case of Linux)
Raspiblitz 1.7.1 on RaspiOS 64

**Electrum client**
Client name (if not upstream desktop Electrum) and version:
No Client

**Additional context**

The relevant changes were after a refactor, however I have been consuming metrics from electrs and was originally able to see things like the size of the mempool, and the number of transactions in the mempool.

After a refactor for v0.9.0, this information is no longer available. What was the motivation behind the refactor and is there an alternative way to get this information?

Relevant commit: https://github.com/romanz/electrs/commit/3780d7d48bdc96db6b0df6f3eb955015e1779a60

FYI, I was using the telegraf setup that is available on the raspiblitz github repository: https://github.com/rootzoll/raspiblitz/tree/v1.7.0/home.admin/assets/telegraf

Here is the line where we consume this information: https://github.com/rootzoll/raspiblitz/blob/v1.7.0/home.admin/assets/telegraf/etc-telegraf/telegraf.d/telegraf_inputs.conf#L280

### PR DESCRIPTION
**Pull request by romanz**
Fixes #551

### CODE REVIEW

**Comment by romanz** [comment]
CC: @dipunm

**Comment by romanz** [comment]
```
$ curl -s localhost:4224 | grep mempool_txs_vsize | head
# HELP mempool_txs_vsize Total vsize of mempool transactions (in bytes)
# TYPE mempool_txs_vsize gauge
mempool_txs_vsize{fee_rate="[                   1,                    2)"} 9883
mempool_txs_vsize{fee_rate="[                   2,                    4)"} 16968
mempool_txs_vsize{fee_rate="[                   4,                    8)"} 4098
mempool_txs_vsize{fee_rate="[                   8,                   16)"} 33795
mempool_txs_vsize{fee_rate="[                  16,                   32)"} 23003
mempool_txs_vsize{fee_rate="[                  32,                   64)"} 1795
mempool_txs_vsize{fee_rate="[                  64,                  128)"} 2255
mempool_txs_vsize{fee_rate="[                 128,                  256)"} 1551
```

**Comment by Kixunil** [comment]
Wow, do I understand correctly that with `electrs` + Prometheus a mempool app like mempool.space is not needed?

**Comment by Kixunil** [comment]
Yeah, I mean Prometheus seems to be lighter-weight if one only wants to see that chart.

**Pull request merged**
